name: setup-temporal
description: Setup Temporal CLI on GitHub Actions runners
inputs:
  version:
    description: Version of Temporal CLI to install (eg. '0.7.0' or 'latest')
    required: false
    default: latest
runs:
  using: node16
  main: dist/setup-temporal/index.js
